services:
    mirakc-recisdb:
      container_name: mirakc-recisdb
      image: mirakc-recisdb
      build:
        context: .
        dockerfile: ./Dockerfile
      init: true
      restart: unless-stopped
      ports:
        - 40772:40772
      volumes:
        - ./config.yml:/etc/mirakc/config.yml:ro
      environment:
        TZ: Asia/Tokyo
        RUST_LOG: info
